"""Regenerate public/growth-data.js from the WHO Child Growth Standards.

The LMS tables come from the WHO Child Growth Standards (2006), as bundled
in the BSD-licensed `pygrowup` package:

    pip download --no-deps pygrowup && tar xzf pygrowup-*.tar.gz
    python3 scripts/extract_who_data.py path/to/pygrowup-x.y.z/pygrowup/tables

Only months 0-36 are kept. WHO publishes two rows for month 24 (recumbent
length and standing height); we keep the length row, matching how the
0-2 year chart ends.
"""
import json
import os
import sys

TABLES = {
    "weight": "wfa_{sex}_0_5_zscores.json",
    "length": "lhfa_{sex}_0_5_zscores.json",
    "head": "hcfa_{sex}_0_5_zscores.json",
}
MAX_MONTH = 36


def load(path):
    rows, seen = [], set()
    for r in json.load(open(path)):
        m = int(r["Month"])
        if m > MAX_MONTH or m in seen:
            continue
        seen.add(m)
        rows.append([m, float(r["L"]), float(r["M"]), float(r["S"])])
    return rows


def main(src):
    data = {}
    for metric, pattern in TABLES.items():
        data[metric] = {}
        for sex, name in (("male", "boys"), ("female", "girls")):
            data[metric][sex] = load(os.path.join(src, pattern.format(sex=name)))
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "public", "growth-data.js")
    with open(out, "w") as f:
        f.write("// Generated by scripts/extract_who_data.py - do not edit by hand.\n")
        f.write("// WHO Child Growth Standards (2006), LMS parameters by month of age.\n")
        f.write("// Rows are [month, L, M, S]. weight in kg, length and head in cm.\n")
        f.write("export const WHO_LMS = ")
        f.write(json.dumps(data, separators=(",", ":")))
        f.write(";\n")
    print("wrote", os.path.normpath(out))


if __name__ == "__main__":
    main(sys.argv[1])
